### ISSUE TITLE
License

### ISSUE THREAD

**Issue by efim0v** [kubAretip/spring-micro-websocket-chat#1]
Good afternoon. First of all, I want to express my gratitude for the opportunity to see your projects, as they are a great example of how to use some technologies. The code is clear and easy to read.
As an author, I have a question for you: can your code be used to educate university students? Your repositories are missing a license file, preventing them from being used. We are not a commercial organization and do not plan to use the code for commercial purposes. Instead, it is planned to organize a small course in which students, taking your code as a basis, will gradually change it, mastering new technologies. It is planned to add the collection of statistics from services, OAuth2.0 integration, etc.
Could you write what is your attitude to this? And whether we have the right to use your code for the purposes described above. If it's easy for you, could you add a license file?

We are interested in the following repositories: https://github.com/kubAretip/spring-micro-websocket-chat.git

- https://github.com/kubAretip/chat-me.git
- https://github.com/kubAretip/chat-me-angular.git
- https://github.com/kubAretip/spring-micro-websocket-chat.git
- https://github.com/kubAretip/spring-micro-websocket-chat-config.git

**Comment by kubAretip** [comment]
No problem. Please feel free to modify

**Comment by efim0v** [comment]
Thanks a lot! 😊
